server:
  port: 8085
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8090/eureka
spring:
  application:
    name: kafka-producer
management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
