server:
  port: ${PORT:8080}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8090/eureka
spring:
  application:
    name: hello-service
management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus