server:
  port: 8088
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
     discovery:
       locator:
         enabled: true
         lower-case-service-id: true
eureka:
  client:
    refresh:
      enable: true
    service-url:
      defaultZone: http://localhost:8090/eureka
logging:
  level:
    root: info